# Generated by Django 4.0.6 on 2022-07-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_csv_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csv_file',
            options={'ordering': ['-datetime'], 'verbose_name': 'csv файл', 'verbose_name_plural': 'csv файлы'},
        ),
        migrations.AlterModelTable(
            name='csv_file',
            table='csv_files',
        ),
    ]
