# Generated by Django 4.0.6 on 2022-07-30 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_csv_file_options_alter_csv_file_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('connection_type', models.CharField(choices=[('CSV', 'CSV file'), ('PG', 'PostgreSQL')], default='CSV', max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'подключение',
                'verbose_name_plural': 'подключения',
                'db_table': 'connections',
                'ordering': ['-datetime'],
            },
        ),
        migrations.AddField(
            model_name='csv_file',
            name='connection_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.connection'),
        ),
    ]
